### PR TITLE
Add profile for JC Holder

### PR DESCRIPTION
**Pull request by jcholder-thoughtworks**
Adds my (simplified) profile. I will likely expand on it soon. Depends on [another pull request](https://github.com/hardware-hack-lab/hardware-hack-lab.github.io/pull/1) for its Mastodon icon.

### CODE REVIEW

**Comment by xuv** [comment]
That's great. While you are at it, don't you want to be "interviewed"? by responding to the questions like in this profile for example: [app/_members/deswaef-julien.md](https://github.com/hardware-hack-lab/hardware-hack-lab.github.io/blob/source/app/_members/deswaef-julien.md)

Or you prefer it just plain simple?

**Comment by jcholder-thoughtworks** [comment]
@xuv I do. That was the later expansion I had in mind.

**Comment by xuv** [comment]
I looked at your branch. There is an issue with your profile image. It's in the wrong folder.
It should be in `app/image/members`

**Comment by jcholder-thoughtworks** [comment]
@xuv Fixed. I'll revisit this profile after I have a local build working.

**Comment by xuv** [comment]
I've updated the project and packages. It should be easier to setup now. 
Also, I've merged this PR. I know it was a draft. But you're on the website, now. :)

**Pull request merged**
